[build]
  publish = "build"
  command = "npm install --legacy-peer-deps && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
<<<<<<< HEAD
  status = 200
=======
  status = 200
>>>>>>> e89316df (netlify)
